version: "3.9"
services:
  blue:
    image: ${IMAGE_TAG}
    container_name: ${APP_NAME}-blue
    ports:
      - "8081:8081" # Map container port 8081 to host port 8081
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
        - mysql
    networks:
      - app-network
  green:
    image: ${IMAGE_TAG}
    container_name: ${APP_NAME}-green
    ports:
      - "8082:8081" # Map container port 8081 to host port 8082
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
        - mysql
    networks:
      - app-network
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - blue
      - green
    networks:
      - app-network
    environment:
      - APP_SERVER=blue
  mysql:
    image: mysql:latest
    networks:
        - app-network
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: yourdb
    healthcheck: # Add a health check
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

networks:
  app-network:
    driver: bridge
